& { $BinaryFormatter = New-Object -TypeName System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
 @{ 
'CheckBox6.Name' = 'CheckBox6'
'chkBlockSignIn.Name' = 'chkBlockSignIn'
'Button1.Name' = 'Button1'
'txtUPN.Name' = 'txtUPN'
'chkLogOut.Name' = 'chkLogOut'
'chkGAL.Name' = 'chkGAL'
'CheckBox4.Name' = 'CheckBox4'
'btnExecute.Name' = 'btnExecute'
'GroupBox1.Name' = 'GroupBox1'
'chkDistroGroups.Name' = 'chkDistroGroups'
'GroupBox2.Name' = 'GroupBox2'
'Label1.Name' = 'Label1'
'btnM365.Name' = 'btnM365'
'CheckBox5.Name' = 'CheckBox5'
'CheckBox7.Name' = 'CheckBox7'
'CheckBox3.Name' = 'CheckBox3'
'chkLicenses.Name' = 'chkLicenses'
'CheckBox2.Name' = 'CheckBox2'
'lblUpn.Name' = 'lblUpn'
'Button3.Name' = 'Button3'
'btnAzureAD.Name' = 'btnAzureAD'
'chkTeams.Name' = 'chkTeams'
'CheckBox1.Name' = 'CheckBox1'
'TextBox2.Name' = 'TextBox2'
'chkSharedMailbox.Name' = 'chkSharedMailbox'
'btnGraph.Name' = 'btnGraph'
'txtOutput.Name' = 'txtOutput'
'$this.Name' = 'Offboard365User'
'TextBox1.Name' = 'TextBox1'
'Button2.Name' = 'Button2'
}
}